version: '3.8'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
       
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mariadb:latest
    restart: unless-stopped
    env_file: ".env"
    volumes:
      - friendica-data:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    # Runs app on the same network as the app container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:app

  redis:
    image: redis:latest
    restart: unless-stopped
    env_file: ".env"
    network_mode: service:app

volumes:
  friendica-data:

networks:
  default:
  